export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_LATELY_SLEEP_PENDING = 'FETCH_LATELY_SLEEP_PENDING';
export const FETCH_LATELY_SLEEP_SUCCESS = 'FETCH_LATELY_SLEEP_SUCCESS';
export const FETCH_LATELY_SLEEP_ERROR = 'FETCH_LATELY_SLEEP_ERROR';
